main:
	Rscript Makefile_acn_notebook.R

 # response:
 # 	pdflatex response.tex
 # 	pdflatex response.tex
 # 	mkdir -p output
 # 	cp -f ./response.pdf ./output/response-lau.pdf


# all: main response

view: ../results/acn_notebook.pdf 

clean:

