---
title: "LCN: Lichen interaction network study"
author: MK Lau
---

<!-- 
rmarkdown::render("./src/lcn_notebook.Rmd", 
	output_format = "pdf_document", 
	output_dir = "./results") 

rmarkdown::render("./src/lcn_notebook.Rmd", 
	output_format = "md_document", 
	output_dir = "./results") 
-->


```{r content, echo = FALSE, results = "hide"}

library(drake)
loadd(tables)
loadd(check.shapiro)
loadd(check.fligner)


```

# Results 

## Tables


### Heritability Values

```{r h2_reml, echo = FALSE}

knitr::kable(tables[["h2_reml"]])

```

### Predictors of Lichen Network Similarity

```{r cn_perm, echo = FALSE}

knitr::kable(tables[["cn"]])

```

### Predictors of Lichen Community Similarity

```{r com_perm, echo = FALSE}

knitr::kable(tables[["com"]])

```

## Statistical Assumption Checks

### Shapiro-Wilks Tests for Normality of Residuals

```{r check_shapiro, echo = FALSE}

check.shapiro[, 2:3] <- apply(check.shapiro[, 2:3], 2, as.numeric)
check.shapiro[, 2:3] <- apply(check.shapiro[, 2:3], 2, round, digits = 5)
knitr::kable(check.shapiro, row.names = FALSE)

```

### Fligner Tests for Homogeneity of Variance

```{r check_fligner, echo = FALSE}

check.fligner[, c("value.statistic", "value.p.value")] <- 
     apply(check.fligner[, c("value.statistic", "value.p.value")],
           2,
           as.numeric)
check.fligner[, c("value.statistic", "value.p.value")] <- 
     apply(check.fligner[, c("value.statistic", "value.p.value")],
           2,
           round, digits = 5)
knitr::kable(check.fligner, row.names = FALSE)

```

